### ISSUE TITLE
Is the advertised profile name case sensitive?

### ISSUE THREAD

**Issue by pgporada** [aarongable/draft-acme-profiles#3]
If a server advertises
```
  "meta": {
    "profiles": {
      "profile1": "https://example.com/docs/profiles#profile1",
      "PrOfIlE2": "https://example.com/docs/profiles#PROFILE2",
    }
  }
}
```

and a client submits a new order specifying the following 
```
  "payload": base64url({
    "profile": "profile2"
    "identifiers": [{"type": "dns", "value": "example.org"}],
  }),
```

* Is it recommended that the server reject that request since the name doesn't match exactly what's advertised? 
* Is it recommended that the server perform normalization on the advertised name and incoming new order request?

**Comment by aarongable** [comment]
Good question! JSON keys are case sensitive, so I think "profile2" and "pROfiLE2" should be considered different -- the client has erred by requesting a non-advertised profile, and the server should reject the request.
